### PR TITLE
Fix model class diagram

### LINKED ISSUE #543: [PE-D][Tester D] Model class diagram does not show that phone number and Telegram handle are optional
Description
The User Guide states that `p/PHONE_NUMBER` and `h/TELEGRAM_HANDLE` are optional fields when adding a contact.

However, in the Developer Guide's Model class diagram, `Person` is associated with `Phone` and `TelegramHandle` without any optional multiplicity such as `0..1`.

This makes the diagram misleading because it suggests that every `Person` must always have a `Phone` and a `TelegramHandle`, even though the application supports contacts without these fields.

Steps to reproduce

1. Open the Developer Guide.
2. Go to the Model component section.
3. Inspect the Model class diagram.
4. Compare it with the User Guide's `add` command format:
   add n/NAME e/EMAIL [p/PHONE_NUMBER] [h/TELEGRAM_HANDLE]

Also test that the app accepts a contact without phone or Telegram handle:
add n/Alice Tan e/alicetan@u.nus.edu

Expected behavior
The Model class diagram should indicate that Phone and TelegramHandle are optional fields, for example using multiplicity 0..1.

Actual behavior
The Model class diagram shows Person associated with Phone and TelegramHandle without optional multiplicity, which implies that these fields are mandatory.

-------------
Labels: `severity.Low` `type.DocumentationBug`

### PR DESCRIPTION
**Pull request by wumingxin238**
Fix #543

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/UndoCommand.java [hunk 1]
```diff
@@ -14,6 +14,11 @@ public class UndoCommand extends Command {
     public static final String MESSAGE_SUCCESS = "Undo successful.";
     public static final String MESSAGE_NO_HISTORY = "No undoable command in history.";
 
+    /**
+    * This command should not be executed directly because undo handling is delegated to
+    * {@code LogicManager}. This method throws an AssertionError to indicate that the command
+    * should not be executed directly.
+    */
```
Comment (wumingxin238) [inline src/main/java/seedu/address/logic/commands/UndoCommand.java:21]: Not sure why this changes. It was supposed to be already updated when I add missing javadoc last week.

**Review by SeePui — APPROVED** [review]
LGTM! But take note updating javadocs also contributes to LOC!

File: src/main/java/seedu/address/logic/commands/UndoCommand.java (hunk 1 above)
Comment (SeePui) [reply src/main/java/seedu/address/logic/commands/UndoCommand.java:21]: Looking at the current master code, it wasn't written yet tho

Comment (wumingxin238) [reply src/main/java/seedu/address/logic/commands/UndoCommand.java:21]: Its so weird, this is my previous updating-DG-branch though
