### PR TITLE
Offline fallback for help

### LINKED ISSUE #497: [PE-D][Tester F] Help command has no fallback without internet
Some users might not be connected to the internet, and if they require the help menu, there is no information available for them. When this actually happens, it might be quite a hassle for such a user.
Perhaps it would be good to have _some_ simple help text, similar to how AB3 does it, so that even without internet, users can get help?

Steps to reproduce: Any valid `help` command.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by nutabi**
Fixes #497.

### CODE REVIEW

**Review by SeePui — APPROVED** [review]
LGTM!

File: src/main/java/seedu/address/logic/commands/HelpCommand.java [hunk 1]
```diff
@@ -57,6 +57,35 @@ public class HelpCommand extends Command {
             "Command \"%s\" does not exist.\nValid commands: "
             + String.join(", ", VALID_COMMAND_NAMES_SORTED);
 
+    /** Prefix added to offline fallback messages. */
+    public static final String OFFLINE_HELP_NOTICE = "User guide unavailable (no internet connection).\n";
```
Comment (sqonky1) [inline src/main/java/seedu/address/logic/commands/HelpCommand.java]: Is this overspecific? Failure to open UG in browser may arise from browser/desktop failures rather than a lack of internet connection.

Maybe a message like "User guide could not be opened in browser." would be more accurate

File: src/main/java/seedu/address/ui/MainWindow.java [hunk 2]
```diff
@@ -166,21 +168,33 @@ private void setWindowDefaultSize(GuiSettings guiSettings) {
...
 
     /**
-     * Opens the given URL in the system default browser.
+     * Checks internet connectivity, then opens the given URL in the system default browser.
+     * Returns {@code true} if the URL was opened successfully, {@code false} otherwise.
      */
-    private void handleHelpUrl(String url) {
+    private boolean handleHelpUrl(String url) {
         try {
+            HttpURLConnection connection = (HttpURLConnection) new URL(url).openConnection();
```
Comment (sqonky1) [inline src/main/java/seedu/address/ui/MainWindow.java:188]: This may be a tradeoff, but it introduces blocking network I/O on the JavaFX UI thread for an action that is pretty common. The 2s timeout may feel unresponsive on slow or unavailable networks, which I feel may be a possible UX concern. Is there a way to check for reachability off JavaFX so the UI doesn't freeze?

File: src/main/java/seedu/address/ui/MainWindow.java [hunk 3]
```diff
@@ -166,21 +168,33 @@ private void setWindowDefaultSize(GuiSettings guiSettings) {
...
+            connection.setConnectTimeout(2000);
+            connection.setReadTimeout(2000);
+            connection.setRequestMethod("HEAD");
```
Comment (sqonky1) [inline src/main/java/seedu/address/ui/MainWindow.java:191]: Does the actual browser-opening path use Desktop.browse(...)? Because if so, would there be possible edge cases where a HEAD request is rejected even when Desktop.browse(...) would work? This may cause false negatives and treat reachable pages as unreachable. Would it be better to try Desktop.browse(...) directly and only fall back if that fails?

File: src/main/java/seedu/address/ui/MainWindow.java (hunk 2 above)
Comment (nutabi) [reply src/main/java/seedu/address/ui/MainWindow.java:188]: The 2s timeout occurs quite rarely actually. In the common scenarios of no internet connection, Github being down, etc. the timeout is almost immediately (I tested this too).

File: src/main/java/seedu/address/logic/commands/HelpCommand.java (hunk 1 above)
Comment (nutabi) [reply src/main/java/seedu/address/logic/commands/HelpCommand.java]: Fair enough. I'll make the change.

File: src/main/java/seedu/address/ui/MainWindow.java (hunk 3 above)
Comment (nutabi) [reply src/main/java/seedu/address/ui/MainWindow.java:191]: I don't think this is possible. HEAD request is simply GET but without response body.

**Comment by calijacked** [comment]
this also fixes #495 right?

**Review by sqonky1 — APPROVED** [review]

**Comment by nutabi** [comment]
Reverting because there are too many changes.
